theme: minima
title: ChocolatierWhoCodes
author: Divya Arora
email: divya@chocolatierwhocodes.githut.io
description: > # this means to ignore newlines until "baseurl:"
  I am TechCurious..FullStackDeveloper..working as Sr.Software Analyst in an Ngo..& who can't live without chocolates...

# social links
twitter_username: ChocolatierWhoCodes # DO NOT include the @ character, or else the build will fail!
github_username:  ChocolatierWhoCodes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
